name: polyellipsoid 
channels:
  - conda-forge
dependencies:
  - freud
  - gmso
  - gsd
  - hoomd=*=*gpu*
  - mbuild
  - numpy
  - pip
  - pytest
  - pytest-cov
  - python
  - pip:
    - git+https://github.com/cmelab/cmeutils.git@master
